api-authentication exercise complete
bryanvaldovinos/c0522-code-solutions pull request #127
Opened 2022-07-20 02:44 UTC by bryanvaldovinos

<img width="859" alt="Screen Shot 2022-07-19 at 7 41 31 PM" src="https://user-images.githubusercontent.com/103273265/179884754-f8ead3cf-c34f-4232-ae4d-d110c3e767d5.png">
<img width="865" alt="Screen Shot 2022-07-19 at 7 30 33 PM" src="https://user-images.githubusercontent.com/103273265/179884758-1ab48de0-816f-48ff-bbb6-cc41a0a32c56.png">

2022-07-20 22:05 UTC, thebearingedge requested changes

2022-07-20 22:05 UTC, thebearingedge commented on api-authentication/server/index.js
> +    });
There should also be a `.catch()` down here in case the database query rejects.

2022-07-20 22:29 UTC, bryanvaldovinos commented
![Screen Shot 2022-07-20 at 3 26 10 PM](https://user-images.githubusercontent.com/103273265/180093356-31e7b16d-5469-4689-a656-9111153c291d.png)

2022-07-21 00:46 UTC, thebearingedge approved these changes

2022-07-26 20:29 UTC, merged