Completed css-two-column-layout exercise. Bryan Valdovinos
bryanvaldovinos/c0522-code-solutions pull request #20
Opened 2022-05-14 00:24 UTC by bryanvaldovinos

<img width="1278" alt="Screen Shot 2022-05-13 at 5 18 26 PM" src="https://user-images.githubusercontent.com/103273265/168403626-7c30dd4d-2cfd-45e2-a3f9-0e2c87323838.png">

2022-05-14 22:57 UTC, codingcodymiller requested changes

2022-05-14 22:57 UTC, codingcodymiller commented on css-two-column-layout/styles.css
> +}
1. Do not number your classes, it gives no insight into their meaning or usage.
2. You should just make this a utility class to apply font family.

2022-05-14 22:57 UTC, codingcodymiller commented on css-two-column-layout/styles.css
> +}
Why not `column-two-thirds`?

2022-05-14 22:57 UTC, codingcodymiller commented on css-two-column-layout/styles.css
> +}
Why not `column-third`?

2022-05-14 22:57 UTC, codingcodymiller commented on css-two-column-layout/styles.css
> +.shrinktext {
If your class name includes multiple words, you should be using `kebab-case`

2022-05-14 22:57 UTC, codingcodymiller commented on css-two-column-layout/styles.css
> +.alignleft {
If your class name includes multiple words, you should be using `kebab-case`

2022-05-14 22:57 UTC, codingcodymiller commented on css-two-column-layout/styles.css
> +.spacebelow {
If your class name includes multiple words, you should be using `kebab-case`

2022-05-14 22:57 UTC, codingcodymiller commented on css-two-column-layout/styles.css
> +.smallertitle {
If your class name includes multiple words, you should be using `kebab-case`

2022-05-14 22:57 UTC, codingcodymiller commented on css-two-column-layout/styles.css
> +.marginbottom {
If your class name includes multiple words, you should be using `kebab-case`

2022-05-14 22:57 UTC, codingcodymiller commented on css-two-column-layout/styles.css
> +.spaceabove {
If your class name includes multiple words, you should be using `kebab-case`

2022-05-14 22:57 UTC, codingcodymiller commented on css-two-column-layout/styles.css
> +.spaceleft {
If your class name includes multiple words, you should be using `kebab-case`

2022-05-14 22:57 UTC, codingcodymiller commented on css-two-column-layout/styles.css
> +.spaceright {
If your class name includes multiple words, you should be using `kebab-case`

2022-05-14 22:57 UTC, codingcodymiller commented on css-two-column-layout/styles.css
> +.margintop {
If your class name includes multiple words, you should be using `kebab-case`

2022-05-16 02:16 UTC, bryanvaldovinos commented
Class Names changed!
<img width="1274" alt="Screen Shot 2022-05-15 at 7 14 15 PM" src="https://user-images.githubusercontent.com/103273265/168508787-4cd328aa-d7d8-4d24-af09-230d694f9d48.png">

2022-05-16 16:16 UTC, codingcodymiller requested changes
In addition to my other comment, I think you may have some rulesets that you never ended up using still in your stylesheet, please verify that you have only included styling that is actually necessary

2022-05-16 16:16 UTC, codingcodymiller commented on css-two-column-layout/styles.css
> +.column {
You should make this `column-full`

2022-05-16 22:15 UTC, codingcodymiller approved these changes
Nice work!!

2022-05-16 22:38 UTC, merged