string manipulation 3 complete
bryanvaldovinos/c0522-code-solutions pull request #73
Opened 2022-06-28 08:16 UTC by bryanvaldovinos

<img width="473" alt="Screen Shot 2022-06-28 at 12 47 18 AM" src="https://user-images.githubusercontent.com/103273265/176129482-69aacbec-2fc9-4822-904a-0df8d0a8c3e3.png">

2022-06-28 18:30 UTC, thebearingedge requested changes

2022-06-28 18:30 UTC, thebearingedge commented on string-manipulation-3/src/is-palindromic.js
> +  }
You can simplify this a bit, since comparison operators return a boolean.

```js
return first.join() === second.join()
```

2022-06-28 23:36 UTC, bryanvaldovinos commented
<img width="461" alt="Screen Shot 2022-06-28 at 3 45 19 PM" src="https://user-images.githubusercontent.com/103273265/176321614-ff1bb7cb-9824-4e0a-b893-202051ab0f6c.png">

2022-06-29 23:28 UTC, thebearingedge approved these changes

2022-06-30 00:16 UTC, merged