express-delete exercise complete
bryanvaldovinos/c0522-code-solutions pull request #90
Opened 2022-07-05 02:37 UTC by bryanvaldovinos

https://user-images.githubusercontent.com/103273265/177238518-bea563fe-d6e3-48e8-abfa-3cfe6a7a58d7.mov

2022-07-05 16:28 UTC, thebearingedge requested changes

2022-07-05 16:28 UTC, thebearingedge commented on express-delete/index.js
> +}
Try reworking your solution to leave out this initial array.

2022-07-06 04:20 UTC, bryanvaldovinos commented
https://user-images.githubusercontent.com/103273265/177467534-078dd504-4fbe-4d88-aac3-f309c69cce77.mov

2022-07-06 14:27 UTC, thebearingedge approved these changes

2022-07-06 19:36 UTC, merged